version: '3.7'

services:
  front:
    build: ./app
    image: supine-front:0.0.1
    ports:
      - '80:80'
    volumes:
      - ./app/code:/www/data


networks:
  default:
    external:
      name: supine