version: '3.7'

services:
  vue-ui:
    build: ./app
    image: supine-vue:0.0.1
    volumes:
      - ./app/code:/app
    networks:
      - supine

  nginx:
    build:
      context: ./app
      dockerfile: Dockerfile-nginx
    image: supine-nginx:0.0.1
    volumes:
      - ./app/code:/www/data
    networks:
      - supine
    ports:
      - "8888:8888"
    

networks:
  supine:
    external:
      name: supine