version: '3.7'

services:
  vue-ui:
    build: ./app
    image: supine-vue:0.0.1
    volumes:
      - ./app/code:/app
    networks:
      - supine

networks:
  supine:
    external:
      name: supine