version: '3.7'

services:
  web:
    build: ./web
    image: supine-web:0.0.1
    depends_on:
      - postgres
    networks:
      - supine
      - default
    volumes:
      - ./web/code:/app

  dg:
    build: ./dg
    image: supine-dg:0.1.0
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - ./dg/code:/app

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - default

networks:
  supine:
    external:
      name: supine
  default:
    driver: bridge